### ISSUE TITLE
function to mask phone numbers

### ISSUE THREAD

**Issue by swanandapps** [swanandapps/stringy-main#7]
**What is needed:**

Function to mask phone numbers, showing only the last four digits.

**Where to Code:**

Find the Contribution Station in `textMaskingAndSecurity.js`.

**Contribution Steps:**

1. Create a development branch out of this issue. (Visible on the right column of the issue)
2. Code your function in that branch.
3. Raise a Pull Request to merge that branch into the main branch.

For more clarity, follow the visual guide in `CONTRIBUTE.md`.

**Comment by suryaraj1** [comment]
@swanandapps could you please assign this to me? 😀

**Comment by ssk090** [comment]
Hey @swanandapps, Please checkout the implementation for the same: https://github.com/swanandapps/stringy-core/pull/31
